### ISSUE TITLE
Warning: This plugin must be either run as root or setuid root.

### ISSUE THREAD

**Issue by saytik** [JasonRivers/Docker-Nagios#82]
After  restarting container. all hosts are DOWN. 
Warning: This plugin must be either run as root or setuid root.

ls -la /opt/nagios/libexec/check_icmp 
-rwsr-xr-x 1 nagios nagios 271424 Oct 16 08:52 /opt/nagios/libexec/check_icmp

Then i run 
chmod u+s  /opt/nagios/libexec/check_icmp 

But when i restart container all hosts are DOWN.  The problem is exist when i have upgraded  container to 4.4.2

my docker-compose (using nagios:latest):

```
services:
  nagios:
    network_mode: "bridge"
    extends:
      file: docker-compose.yml
      service: nagios 
    container_name: nagios 
    environment:
      VIRTUAL_HOST: my.domain.com
      MAIL_RELAY_HOST: ${MAIL_RELAY_IP}
      NAGIOS_FQDN: my.domain.com
      NAGIOS_TIMEZONE: Europe/Kiev 
    volumes:
      - /data/nagios/etc/:/opt/nagios/etc/
      - /data/nagios/var:/opt/nagios/var/
      - /data/nagios/custom-plugins:/opt/Custom-Nagios-Plugins
      - /data/nagios/nagiosgraph-var:/opt/nagiosgraph/var \
      - /data/nagios/nagiosgraph-etc:/opt/nagiosgraph/etc \
```

**Comment by saytik** [comment]
don't have this problem with 4.4.1 version. Rollback to 4.4.1

**Comment by saytik** [comment]
Hi Jason,

When will image with nagios core 4.4.3  be available ? 
(nagios core 4.4.3 has bugfix with notification fromservice soft state)
Thanks

**Comment by saytik** [comment]
as i see 4.4.3 can be used with latest tag, cool.
Also,  i have found the problem with check_icmp, need to use check_ping instead ... 
In my template was set:
check_command                   check-host-icmp
I have fixed back to check-host-alive, where check_ping is used.

**Comment by JasonRivers** [comment]
The :latest image is running 4.4.3, I don't tag the version on dockerhub until the following version, so the "latest" should always be the latest version, There's no real reason for not tagging at release time, other than I do maintenance between, so would just create a merge when I bump the version.

Let me know if this solves your issue!

**Comment by saytik** [comment]
I have solved  by switching  check_icmp to check_ping. 
But the command  check_icmp has no problem  with version 4.4.1,  and the problem is in 4.4.2 and latest 

4.4.1:
# ls -la /opt/nagios/libexec/check_icmp
-rwsr-xr-x 1 nagios nagios 271424 Jan 23 12:35 /opt/nagios/libexec/check_icmp
# sudo -u nagios -i /opt/nagios/libexec/check_icmp -H 127.0.0.1
OK - 127.0.0.1: rta 0.039ms, lost 0%|rta=0.039ms;200.000;500.000;0; pl=0%;40;80;; rtmax=0.058ms;;;; rtmin=0.031ms;;;; 

latest:
# ls -la /opt/nagios/libexec/check_icmp
-r-xr-xr-x 1 nagios nagios 271424 Jan 23 12:35 /opt/nagios/libexec/check_icmp
# sudo -u nagios -i /opt/nagios/libexec/check_icmp -H 127.0.0.1
Warning: This plugin must be either run as root or setuid root.
To run as root, you can use a tool like sudo.
To set the setuid permissions, use the command:
	chmod u+s yourpluginfile
check_icmp: Failed to obtain ICMP socket: Operation not permitted

chmod u+s /opt/nagios/libexec/check_icmp  doesn't helps

**Comment by viperk1** [comment]
Can't believe this problem is still around, lol. @JasonRivers has there been any update on getting the check_icmp fixed? I can change the permissions inside the container and it works for a while, but I can't get it to work from a fresh create.
